import type { Metadata } from 'next';
import { Bayon, Merriweather_Sans } from 'next/font/google';
import '../../asset/root.css';
import { Toaster } from 'sonner';

const bayonFont = Bayon({
  variable: '--font-bayon',
  weight: ['400'],
  subsets: ['khmer'],
});

const merriweatherSans = Merriweather_Sans({
  variable: '--font-weather',
  subsets: ['cyrillic-ext'],
  style: ['italic', 'normal'],
});

export const metadata: Metadata = {
  title: 'Portfolio Dashboard',
  //   description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bayonFont.variable} ${merriweatherSans.variable} body-background`}
      >
        <Toaster />

        {children}
      </body>
    </html>
  );
}
